const quotes = [
  "Believe you can and you're halfway there.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Don’t stop until you’re proud.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The future depends on what you do today.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "If you can dream it, you can do it.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Difficult roads often lead to beautiful destinations.",
  "Believe in yourself and all that you are.",
  "Your only limit is your mind.",
  "Little things make big days.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Success is what happens after you have survived all your mistakes.",
  "You don't have to be great to start, but you have to start to be great.",
  "If you want it, work for it.",
  "It's going to be hard, but hard does not mean impossible.",
  "Success is the sum of small efforts repeated day in and day out.",
  "You are capable of amazing things.",
  "Act as if what you do makes a difference. It does.",
  "Stay positive, work hard, make it happen.",
  "Opportunities don't happen, you create them.",
  "You have within you right now, everything you need to deal with whatever the world can throw at you."
]

export default quotes
